name: Build

on:
  push:
    branches:
      - master
    tags:
      - "*"

  workflow_dispatch:

concurrency:
  group: build-main
  cancel-in-progress: true

jobs:
  build:
    uses: wxn0brP/workflow-dist/.github/workflows/build-ts.yml@main
    with:
      scriptsHandling: "remove-all"
      publishToNpm: true
      customCommands: |
        curl https://raw.githubusercontent.com/wxn0brP/VQL/refs/heads/types/vql.d.ts > src/vql.ts
        npm run minify
    
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}